name: Add a Language Translation
description: Contribute a language translation
body:
  - type: textarea
    attributes:
      label: System Language
      description: You can find this in the SimpleDeckyTDP Plugin's UI, full guide here https://github.com/aarron-lee/SimpleDeckyTDP/blob/main/documentation/add_language.md
    validations:
      required: true
  - type: textarea
    attributes:
      label: Translations
      description: Translations of all terms
    validations:
      required: true
