name: Issue report
description: File an issue report
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: checkboxes
    attributes:
      label: Did you try a full reinstall of the plugin?
      description: You can reinstall via the quick install script in the README
      options:
        - label: The issue still exists even after a reinstall
          required: true
  - type: checkboxes
    attributes:
      label: Did you already try resetting your plugin settings?
      description: You can delete plugin settings via `rm $HOME/homebrew/settings/SimpleDeckyTDP/settings.json`, and then rebooting your device
      options:
        - label: I can confirm that the issue is still present after fully deleting plugin settings
          required: true
  - type: textarea
    attributes:
      label: Bug Description
      description: A concise description of the issue you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the issue (if you know how to)
      placeholder: |
        1. set TDP via slider
        2. perform a suspend-resume cycle
        3. issue shows up afterwards
    validations:
      required: false
  - type: textarea
    attributes:
      label: Hardware information
      description: |
        examples:
          - **Distro**: SteamOS 3.6.15 (`cat /etc/os-release`)
          - **CPU**: 32-core AMD Ryzen Threadripper 7970X (`inxi` or `cat /proc/cpuinfo`)
          - **GPU**: Advanced Micro Devices [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] (`lspci -nn | grep VGA` or `lshw -C display -numeric` or `vulkaninfo --summary | grep deviceName`
      value: |
        - Distro:
        - CPU:
        - GPU:
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs, screenshots, or anything else
      description: |
        Please include any relevant logs or screenshots that will give us more context about the issue you are reporting.

        You can find logs for SimpleDeckyTDP in "~/homebrew/logs/SimpleDeckyTDP/"

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
